version: "3"

services:

  user-service:
    build: ./api-services
    image: spring-zuul/user-service:latest
    container_name: user-service
    ports:
      - "9090:9090"
    environment:
      - JAVA_OPTS=  # override here if needed
    depends_on:
      - db
    networks:
      - local

  zuul-service:
    build: ./api-gateway
    image: spring-zuul/zuul-service:latest
    container_name: zuul-service
    ports:
      - "8080:8080"
    networks:
      - local

  db:
    image: mysql:8
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=users
    networks:
      - local

networks:
  local:
